name: print-name
on: 
  push:
    branches:
      - main
jobs:
  print-name-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print Message
        run: echo "Hello from print-name workflow"

